#!/usr/bin/bash

script_dir=$(dirname "$0")
tool_gen_ast=gen_ast
default_ast_output_dir=$script_dir/src/com/craftinginterpreters/lox

if [ "$1" = "$tool_gen_ast" ]; then
    if [ "$#" -eq 2 ]; then
        java -cp ${script_dir}/bin com.craftinginterpreters.tool.GenerateAst "$2"
    else
        java -cp ${script_dir}/bin com.craftinginterpreters.tool.GenerateAst ${default_ast_output_dir}
    fi
else
    java -cp ${script_dir}/bin com.craftinginterpreters.lox.Lox "$@"
fi